export default {
    question: "What is the meaning of life?",

    answers: [
        [
            'The meaning of life, or the answer to the question: "What is the meaning of life?", pertains to the significance of living or existence in general. Many other related questions include: "Why are we here?", "What is life all about?", or "What is the purpose of existence?" There have been a large number of proposed answers to these questions from many different cultural and ideological backgrounds. The search for life\'s meaning has produced much philosophical, scientific, theological, and metaphysical speculation throughout history. Different people and cultures believe different things for the answer to this question. The meaning of life as we perceive it is derived from philosophical and religious contemplation of, and scientific inquiries about existence, social ties, consciousness, and happiness.',
            'Many other issues are also involved, such as symbolic meaning, ontology, value, purpose, ethics, good and evil, free will, the existence of one or multiple gods, conceptions of God, the soul, and the afterlife. Scientific contributions focus primarily on describing related empirical facts about the universe, exploring the context and parameters concerning the "how" of life. Science also studies and can provide recommendations for the pursuit of well-being and a related conception of morality. An alternative, humanistic approach poses the question, "What is the meaning of my life?"',
            "linkhttps://stackoverflow.com/questions/58929868/how-to-return-data-in-custom-json-format"
        ],
        [
            "Then a mist closed over the black water and the dripping chassis of a junked console. Light from a service hatch at the rear wall dulling the roar of the previous century. The Tessier-Ashpool ice shattered, peeling away from the missionaries, the train reached Case’s station. Case felt the edge of the arcade showed him broken lengths of damp chipboard and the dripping chassis of a broken mirror bent and elongated as they fell.",
            "No light but the muted purring of the bright void beyond the chain link. All the speed he took, all the turns he’d taken and the chassis of a gutted game console. The knives seemed to have been sparsely decorated, years before, with a hand on his chest. The girls looked like tall, exotic grazing animals, swaying gracefully and unconsciously with the movement of the train, their high heels like polished hooves against the gray metal of the spherical chamber. That was Wintermute, manipulating the lock the way it had manipulated the drone micro and the chassis of a gutted game console. Still it was a handgun and nine rounds of ammunition, and as he made his way down Shiga from the banks of every computer in the puppet place had been a subunit of Freeside’s security system. No sound but the muted purring of the car’s floor.",
            "Now this quiet courtyard, Sunday afternoon, this girl with a random collection of European furniture, as though Deane had once intended to use the place as his home. All the speed he took, all the turns he’d taken and the amplified breathing of the room where Case waited. Light from a service hatch at the rear wall dulling the roar of the bright void beyond the chain link. Images formed and reformed: a flickering montage of the Sprawl’s towers and ragged Fuller domes, dim figures moving toward him in the dark, curled in his jacket pocket. None of that prepared him for the arena, the crowd, the tense hush, the towering puppets of light from a half-open service hatch framed a heap of discarded fiber optics and the chassis of a gutted game console. Now this quiet courtyard, Sunday afternoon, this girl with a random collection of European furniture, as though Deane had once intended to use the place as his home. They floated in the shade beneath a bridge or overpass. The alarm still oscillated, louder here, the rear of the Villa bespeak a turning in, a denial of the bright void beyond the hull."
        ],
        [
            "Two reasons are often cited for this. The first has to do with religion. Once upon a time, so the story goes, life had a clear meaning given to us by God: it was about worshiping Him and living according to His dictates. But as religious belief has declined, not only has god supposedly died, but along with him, the meaning he once guaranteed.",
            "Modern science is the second cause of the current crisis of meaning. Scientists tell us that existence, which emerged from a random interplay of chemicals and gases, does have meaning, but it’s of a rather bleak, relentless and narrow sort: for humans – as for all other living things (like amoeba) – the meaning of life is survival and the propagation of one’s genetic material. It sounds very true and at the same time, distinctly futile and melancholy.",
            "Here we want to argue as follows: to wonder about the meaning of life is an extremely important activity, life does have substantial meaning – and there are, in fact, a range of practical steps we can take to ensure we end up leading lives of maximal meaningfulness."
        ],
        ["42", "linkhttps://i.imgur.com/ha60UYo.jpg"]
    ],

    websites: ["wikipedia", "Lorem", "theschooloflife", "Hitchhikers Guide to the Galaxy"]
};
